##Problem 2 
#### Part(c)
#### Calculation for (a-i)

In [32]:

from scipy.linalg import svd
import numpy as np
from numpy.linalg import eig

A = np.array([[1, 1], [1, 1], [1, -1]])

U, s, VT = svd(A)
print("Left singular vector = \n",np.around(U, decimals=1))
print("\nSigma = ",np.around(s, decimals=1))
print("\nRight singular vector = \n",np.around(VT, decimals=1))
A = np.array([[1, 1], [1, 1], [1, -1]])
AT=A.T
AAT=np.dot(A,AT)
w_AAT,v_AAT=eig(AAT)
A = np.array([[1, 1], [1, 1], [1, -1]])
AT=A.T
ATA=np.dot(A.T,A)
w_ATA,v_ATA=eig(ATA)
print("Eigen vector of A * A^T is \n",np.around(v_AAT, decimals=1)," \n Interchanging column 2 column 3 and multipying it by -1 we will get\n",np.array([[-0.7, 0,-0.7], [-0.7, 0,0.7], [0,1, 0]]) )

print("Which is equal to Right singular vector")
print("Eigen vector of A^T * A is \n",np.around(v_ATA, decimals=1), "Which is equal to Left singular vector after multiplying matrix with -1 and interchanging rows")

Left singular vector = 
 [[-0.7 -0.  -0.7]
 [-0.7 -0.   0.7]
 [-0.   1.   0. ]]

Sigma =  [2.  1.4]

Right singular vector = 
 [[-0.7 -0.7]
 [ 0.7 -0.7]]
Eigen vector of A * A^T is 
 [[ 0.7 -0.7  0. ]
 [ 0.7  0.7  0. ]
 [ 0.   0.   1. ]]  
 Interchanging column 2 column 3 and multipying it by -1 we will get
 [[-0.7  0.  -0.7]
 [-0.7  0.   0.7]
 [ 0.   1.   0. ]]
Which is equal to Right singular vector
Eigen vector of A^T * A is 
 [[ 0.7 -0.7]
 [ 0.7  0.7]] Which is equal to Left singular vector after multiplying matrix with -1 and interchanging rows


#### Calculation for (b-i)
#### SInce we need only rank 1 so we need the eigenvalues associated with highest eigen value. SVD function gives us ordered values hence using SVD

In [95]:
A = np.array([[1, 1], [1, 1], [1, -1]])
u, s, vh = np.linalg.svd(A, full_matrices=False)
U1 = u[:,:1]
S1 = np.diag(s[:1])
V1 = vh[:1]
rank1M = np.dot(U1, np.dot(S1, V1))
print("Best rank approximation for A is\n",np.around(rank1M,decimals=1))
print(" The approximation error is ",np.sum(np.around(A-rank1M,decimals=1)**2))

Best rank approximation for A is
 [[1. 1.]
 [1. 1.]
 [0. 0.]]
 The approximation error is  2.0
